#16 admin panel
Freezy-Ice/Web pull request #27
Opened 2022-01-07 22:49 UTC by Ola-M

Closes #16

2022-01-07 22:51 UTC, Ola-M commented
![image](https://user-images.githubusercontent.com/56175718/148617236-edc0dd99-1989-4cd0-b5c7-30f2408eb683.png)
![image](https://user-images.githubusercontent.com/56175718/148617258-0d580708-e36d-4b1c-afdb-3cbfdef49085.png)
![image](https://user-images.githubusercontent.com/56175718/148617308-15e990c1-0ec5-45d9-aff4-e6e85cf461e7.png)

2022-01-07 23:02 UTC, Skrabka98 requested changes

2022-01-07 23:02 UTC, Skrabka98 commented on freezy-ice-web/src/Components/AdminPanel/AcceptingShopDetails.tsx
> +        },
Unused

2022-01-07 23:02 UTC, Skrabka98 commented on freezy-ice-web/src/Components/Modals/CategoryModal.tsx
> +);
unused

2022-01-07 23:02 UTC, Skrabka98 commented on freezy-ice-web/src/Store/Reducer/ShopAdmin/action.ts
> +    console.log('action', result);
log

2022-01-08 22:08 UTC, Skrabka98 approved these changes

2022-01-08 22:09 UTC, merged